artifact_uri: file:///c:/Users/simle/OneDrive/Documents/Apexon/MLFlow/mlruns/0/8babdfc48e604c5ba8eb4dff417b9501/artifacts
end_time: 1697655355332
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8babdfc48e604c5ba8eb4dff417b9501
run_name: youthful-croc-814
run_uuid: 8babdfc48e604c5ba8eb4dff417b9501
source_name: ''
source_type: 4
source_version: ''
start_time: 1697655351340
status: 3
tags: []
user_id: simle
