artifact_uri: file:///c:/Users/simle/OneDrive/Documents/Apexon/MLFlow/mlruns/0/343b1a02721b4085ad98c4d41e8be527/artifacts
end_time: 1697468540220
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 343b1a02721b4085ad98c4d41e8be527
run_name: valuable-colt-82
run_uuid: 343b1a02721b4085ad98c4d41e8be527
source_name: ''
source_type: 4
source_version: ''
start_time: 1697468536030
status: 3
tags: []
user_id: simle
