artifact_uri: file:///c:/Users/simle/OneDrive/Documents/Apexon/MLFlow/mlruns/0/36111dbdee36491094326311bdcfda0f/artifacts
end_time: 1697656791232
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 36111dbdee36491094326311bdcfda0f
run_name: bemused-rat-395
run_uuid: 36111dbdee36491094326311bdcfda0f
source_name: ''
source_type: 4
source_version: ''
start_time: 1697656787104
status: 3
tags: []
user_id: simle
