artifact_uri: file:///c:/Users/simle/OneDrive/Documents/Apexon/MLFlow/mlruns/0/7285165f4cd24a32aafb9b2c380c2a7c/artifacts
end_time: 1697656775993
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7285165f4cd24a32aafb9b2c380c2a7c
run_name: sneaky-grouse-193
run_uuid: 7285165f4cd24a32aafb9b2c380c2a7c
source_name: ''
source_type: 4
source_version: ''
start_time: 1697656771909
status: 3
tags: []
user_id: simle
