artifact_uri: file:///c:/Users/simle/OneDrive/Documents/Apexon/MLFlow/mlruns/0/d4b2b33fe4fb4b3c826fe8543bca1e1f/artifacts
end_time: 1697651860953
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d4b2b33fe4fb4b3c826fe8543bca1e1f
run_name: defiant-chimp-767
run_uuid: d4b2b33fe4fb4b3c826fe8543bca1e1f
source_name: ''
source_type: 4
source_version: ''
start_time: 1697651856718
status: 3
tags: []
user_id: simle
