artifact_location: file:///c:/Users/simle/OneDrive/Documents/Apexon/MLFlow/mlruns/0
creation_time: 1697466607117
experiment_id: '0'
last_update_time: 1697466607117
lifecycle_stage: active
name: Default
