artifact_uri: file:///c:/Users/simle/OneDrive/Documents/Apexon/MLFlow/mlruns/0/4e24f30b8d754ac6aad0933fc53a83a5/artifacts
end_time: 1697656806097
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4e24f30b8d754ac6aad0933fc53a83a5
run_name: skillful-wolf-840
run_uuid: 4e24f30b8d754ac6aad0933fc53a83a5
source_name: ''
source_type: 4
source_version: ''
start_time: 1697656802039
status: 3
tags: []
user_id: simle
