artifact_uri: file:///c:/Users/simle/OneDrive/Documents/Apexon/MLFlow/mlruns/0/60b9ae02045845abadf30657e85249d4/artifacts
end_time: 1697656441137
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 60b9ae02045845abadf30657e85249d4
run_name: rumbling-mole-985
run_uuid: 60b9ae02045845abadf30657e85249d4
source_name: ''
source_type: 4
source_version: ''
start_time: 1697656437040
status: 3
tags: []
user_id: simle
