artifact_uri: file:///c:/Users/simle/OneDrive/Documents/Apexon/MLFlow/mlruns/0/9ca4594cd1a04e96b9c006db57f4a11c/artifacts
end_time: 1697468183480
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9ca4594cd1a04e96b9c006db57f4a11c
run_name: smiling-ray-807
run_uuid: 9ca4594cd1a04e96b9c006db57f4a11c
source_name: ''
source_type: 4
source_version: ''
start_time: 1697468177444
status: 3
tags: []
user_id: simle
