artifact_uri: file:///c:/Users/simle/OneDrive/Documents/Apexon/MLFlow/mlruns/0/e622899786fe4f8fbdd57de928ff64f7/artifacts
end_time: 1697649626261
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e622899786fe4f8fbdd57de928ff64f7
run_name: debonair-goose-54
run_uuid: e622899786fe4f8fbdd57de928ff64f7
source_name: ''
source_type: 4
source_version: ''
start_time: 1697649620472
status: 3
tags: []
user_id: simle
