artifact_uri: file:///c:/Users/simle/OneDrive/Documents/Apexon/MLFlow/mlruns/0/87b37a0b8a94447abc55f7828849b4e6/artifacts
end_time: 1697655225258
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 87b37a0b8a94447abc55f7828849b4e6
run_name: unleashed-quail-805
run_uuid: 87b37a0b8a94447abc55f7828849b4e6
source_name: ''
source_type: 4
source_version: ''
start_time: 1697655221390
status: 3
tags: []
user_id: simle
